version: '3.1'
services:
  db:
    image: mysql
    container_name: gerenciador-projetos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciador-projetos
    ports:
      - "3306:3306"
    volumes:
      - gerenciadorprojetos:/var/lib/mysql

volumes:
  gerenciadorprojetos: